### ISSUE TITLE
Individual annotation for each read

### ISSUE THREAD

**Issue by Ales-ibt** [mreppell/Karp#4]
Hello,

I am making a benchmark of your taxonomic annotation method with a in silico simulated dataset, so I know the identity of each 16S read a priori. To evaluate the performance of Karp with this dataset, I need the list of the corresponding taxonomical id to each read in the input. I couldn't find any flag useful in karp quantify command to print such list, that is why I am asking now if there is some script that could be modified to print or to not erase, the file that I need.

Thank you so much and have a great day.

Alejandra.

**Comment by mreppell** [comment]
Hi Alejandra,

Thank you for your interest in Karp. Rather than hard assignments to a particular reference, Karp estimates the relative probabilities of taxa using information from across the reads during the EM algorithm. In a sense though, after the EM has converged the reads could be probabilistically assigned to specific references, in other words if the probability a read came from reference A was 90% and from reference B was 10% it would divide and add 0.9 reads to the count of A and 0.1 reads to the count of B. Karp does not have an immediate way to output that information, but if would be valuable to you let me know and I could possibly add a new option in the future.

Thank you,

Mark

**Comment by Ales-ibt** [comment]
Thank you Mark for your answer,

So if I understand well, it means that I can not evaluate the method sensibility by read, I just can evaluate the global diversity in terms of taxa richness and its abundance, is that right?  Actually, the method seems to me a little complicated because of the mathematics and probabilistic foundation. Either way, it sounds like you assume that a read could come from more than one reference, and in that case, you are dividing the abundance instead to look for the LCA. That is interesting.

It is a pity that there is no way by the time to evaluate the method as I expected. Anyway, I keep track of the modifications in later versions of Karp.

Kind regards,


Ales.

**Comment by mreppell** [comment]
Hi Ales,

I just wanted to make you aware that I have added a new option to Karp, --readinfo, which outputs an additional file that contains the posterior probabilities assigned to each read after the EM algorithm has converged. Thank you again for your interest in Karp, and let me know if you have any questions or problems.

Mark
