### ISSUE TITLE
16S reference best practices

### ISSUE THREAD

**Issue by solna86** [mreppell/Karp#7]
Thanks for creating Karp. It is great that someone has ported the ideas from Sailfish and Kallisto, quantification as EM inference on k-mer distributions, to 16S where they make so much sense too.

I am experiencing some unstable quantification results using some poor quality low-depth 16S V4 read datasets. I was wondering if there are any best practices on what 16S reference database to use, as a changing the reference seems to have a dramatic impact on the estimated abundances. Even the most abundant species change entirely.

Perhaps I am doing something terribly wrong, as I am naively using the following two references from SILVA:

1. https://ftp.arb-silva.de/current/Exports/SILVA_138_SSURef_NR99_tax_silva.fasta.gz
1. https://ftp.arb-silva.de/current/Exports/SILVA_138_SSURef_tax_silva.fasta.gz

The first one is a minimal reference with ~5e5 entries. ~4.5e5 are bacteria or archaea. I haven't removed other domains of life. The second one contains ~2.2e6 entries, with ~2e6 bacteria or archaea. I haven't removed other domains of life either.

**Comment by mreppell** [comment]
Hi Solna86,

Thank you for your comment. My recent research has not included microbiome work, so I would not be the best resource for resolving which reference is currently the best to work from, but I can give some general thoughts.

First, with what you describe as poor quality and low-depth reads from a single hyper-variable region it may make more sense to look at a rougher taxonomic classification than species level. These might be more stable. Species level quantification from a single hyper-variable region can be difficult because many species may not vary at all across such a short sequence length.

In general I would recommend using the broadest reference dataset possible for which Karp can make an index. When references are too large and diverse the kmer index can be computationally prohibitive. But, if the index can be created with your compute resources, then the bigger the better. Karp has a likelihood threshold (--like_thresh and --max_like_out parameters) that filters out reads that don't map to anything in your database, but it possible that those would map to something in a broader database.

I hope this is helpful,

Mark Reppell

**Comment by solna86** [comment]
Thanks for your detailed reply.

For future reference of other people reading this, SILVA is probably the best 16S database [1].

As you pointed out, short and noisy 16S are very problematic. I will try to obtain longer reads with less noise for the same experiment and try Karp and others again.

In case of noisy reads, DADA2 does a decent job at estimating rough taxa classification.

Best wishes.

[1] https://www.arb-silva.de/
